# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 81d97ee3e066e7c1092a9b6e23b83e7c79e0c69b76a3fa840c2d216cb33c096caffdcacd0c05f57209df4639805b73ab6c827585be4ac011cd60db34ad761f6b

test:
  secret_key_base: 2e8edeb68963846ec611b3c32399340476b9ad4af3a5b2b760376442e2b88b8545f9b014a132dab5263a92bdf7f3f947c6f32029cab517fb36feef9fbe506b28

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
