# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: becd192d0eba31e6b1f67395f6a9d3546e6f3ac744b85552ca30c0c297dc3183de5a66046201536da8037e8c8727b769dc9e89e59622f83de29963183027ecc2

test:
  secret_key_base: dc74e872405679ab12e6b70a7d2bbea33e2317b037be020fd3d82e4a8bd58c3cf219e58aabc266c7bb8dbdc8a9731c89bd03d0c90ab0fc41fa5df6fed86080f7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
